name: nikola
version: 7.8.1
summary: A static website generator
description: A static website generator
confinement: strict
grade: stable

apps:
    nikola:
         command: nikola.sh
         plugs: [network, network-bind, home]

parts:
    nikola-script:
        plugin: dump
        source: script
    nikola:
        source: git://github.com/getnikola/nikola.git
        source-tag: v7.8.1
        stage-packages:
            - locales
            - libc-bin
        plugin: python
        build-packages: [libjpeg-dev]
