name: nikola
version: 7.8.1
summary: A static website generator
description: A static website generator
confinement: strict
grade: stable

apps:
    nikola:
         command: nikola
         plugs: [network, network-bind, home]

parts:
    nikola:
        plugin: python
        python-packages:
            - nikola
            - pillow
        python-version: python3
        build-packages: [libjpeg-dev]
